---
spring:
  profiles:
    active: dev
---
server:
  port: 8082
spring:
  datasource:
    username: ShaoBin
    password: a88675577
    url: jdbc:mysql://localhost:3306/MapleTravel?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
  profiles: dev
---
#server:
#  port: 8082
#spring:
#  datasource:
#    username: root
#    password: ShaoBin
#    url: jdbc:mysql://localhost:3306/BadgerMarket?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
#  profiles: prod
#---